In [3]:
import numpy as np

x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
print(x)
print(y)


[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [4]:
y2 = x[1:2, [0,1,0]]
print(y2)


[[3 4 3]]


In [5]:
y3 = x[x>2]
print(y3)


[3 4 5 6]


In [6]:
r = range(5)
lt = list(r)
print(iter(lt))
for i in iter(lt):
    print(i)
print('')


0
1
2
3
4



In [7]:
a17 = np.array([1,2,3,4])
for i in a17:
    print(i)
print('')

1
2
3
4



In [8]:
for i2 in np.nditer(a17):
    print(i2)

1
2
3
4


In [9]:
list3 = [[1,2],[3,4]]
for i2 in list3:
    print(i2)


[1, 2]
[3, 4]


In [10]:
a18 = np.array(list3)
for i2 in a18:
    print(i2)
print(a18.shape)


[1 2]
[3 4]
(2, 2)


In [12]:
for i2 in np.nditer(a18):
    print(i2)


1
2
3
4


In [13]:
list4 = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
a19 = np.array(list4)
for i2 in a19:
    print(i2)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [14]:
for i2 in np.nditer(a19):
    print(i2)

0
1
2
3
4
5
6
7
8
9
10
11
