In [5]:
import numpy as np

print("Make Array")
a = np.array([1,2,3,4])
print(a, a.shape, a.ndim)

print("Double Array")
l = [[1,2],[3,4]]
print(l[0][0])

print("Make double array")
a1 = np.array([[1,2],[3,4]])

print("Array, shape, ndim")
print(a1, a1.shape,a1.ndim)
l2 = [[[1,2],[2,3]]]

print("Array 1 to 12")
a2 = np.array(l2)
print(a2,a2.shape,a2.ndim)
print(l2[0][0][1])

print("Make double array another way\n")
a3 = np.array([1,2,3,4,5], ndmin=2)
print(a3.shape, a3.ndim, a3.dtype)

print("Make array, other type(float)")
a4 = np.array([1,2,3], dtype=float)
print(a4.shape, a4.ndim, a4.dtype)

print("Make double string array")
student = np.dtype([('name', 'S20'),('age','i1')])
print(student)

print("Make double array typed (student) / shape, ndim")
a5 = np.array([('test1',20),('test2',30)], dtype =student)
print(a5)
print(a5.shape, a5.ndim)

print("make Empty Array, typed int")
a6 = np.empty([4,3], dtype = int)
print(a6)

print("Make zero array, typed int")
a7 = np.zeros((10,), dtype=np.int)
print(a7)

print("make ones array, typed int")
a8 = np.ones([2,2], dtype=int)
print(a8)

Make Array
[1 2 3 4] (4,) 1
Double Array
1
Make double array
Array, shape, ndim
[[1 2]
 [3 4]] (2, 2) 2
Array 1 to 12
[[[1 2]
  [2 3]]] (1, 2, 2) 3
2
Make double array another way

(1, 5) 2 int64
Make array, other type(float)
(3,) 1 float64
Make double string array
[('name', 'S20'), ('age', 'i1')]
Make double array typed (student) / shape, ndim
[(b'test1', 20) (b'test2', 30)]
(2,) 1
make Empty Array, typed int
[[2305843009213693979 2305843009213693952                  26]
 [        12884901906                   0        360777252985]
 [                  0                   0                   0]
 [                  0                   0                   0]]
Make zero array, typed int
[0 0 0 0 0 0 0 0 0 0]
make ones array, typed int
[[1 1]
 [1 1]]


In [6]:
a9 = np.arange(10, dtype = float)
print(a9)

a10 = np.arange(10, 20, 2)
print(a10)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[10 12 14 16 18]


In [7]:
a11 = np.linspace(10, 20, 5)
print(a11)

a12 = np.linspace(1, 2, 5)
print(a12)

[10.  12.5 15.  17.5 20. ]
[1.   1.25 1.5  1.75 2.  ]


In [9]:
a13 = np.arange(10)
print(a13)

a14 = slice(2,7,2)
print(a13[a14])
print(a13[2:7:2])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]
