In [1]:
import numpy as np

x= np.arange(15).reshape((3,5))
print(x, x.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)


In [2]:
x2 = x.T
print(x2, x2.shape)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] (5, 3)


In [3]:
x3 = np.transpose(x)
print(x3, x3.shape)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] (5, 3)


In [4]:
x4 = np.swapaxes(x, 0, 1)
print(x4, x4.shape)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] (5, 3)


In [6]:
x5 = [[1,2], [3,4], [5,6]]
x6 = np.array(x5)
print(x6.shape, x6.ndim) # 0,1

(3, 2) 2


In [7]:
x7 = x6.T
print(x7.shape, x7.ndim)

(2, 3) 2


In [8]:
print(x6)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
print(x7)

[[1 3 5]
 [2 4 6]]


In [10]:
print(np.transpose(x6))

[[1 3 5]
 [2 4 6]]


In [11]:
print(np.swapaxes(x6,0,1))

[[1 3 5]
 [2 4 6]]
