In [12]:
import numpy as np
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [10]:
data = np.random.randn(7,4)
data[data<0]=0
print(data)

[[0.58965219 0.04123073 0.         0.1504309 ]
 [0.31789546 0.         0.         1.11826847]
 [0.09496874 0.         0.         0.        ]
 [0.         0.         0.4518427  0.70587099]
 [0.14290541 0.         0.06064035 0.        ]
 [0.23080128 0.         1.03328795 0.62661672]
 [0.         0.         0.         0.77997502]]


In [3]:
data[names != 'Joe'] =7
print(data)


[[7.         7.         7.         7.        ]
 [0.9345702  1.20337743 0.         0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.1768581  0.22356824 0.         0.        ]
 [0.         0.58977831 0.62335483 0.81719557]]


In [4]:
arr = np.arange(15).reshape((3,5))
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
print(arr.T)


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [6]:
arr = np.random.randn(6,3)
print(arr)


[[ 0.60829477 -0.96789147 -0.42237141]
 [-0.36239979  1.4865812   0.72577381]
 [-0.31499826 -0.80730632 -0.20016547]
 [-0.14107452  1.17744228 -0.75395173]
 [ 0.70333034 -0.17739741 -0.21219281]
 [ 0.17937561 -0.74451913  0.52506092]]


In [7]:
print(np.dot(arr.T, arr))


[[ 1.14733124 -1.29762461 -0.40558996]
 [-1.29762461  5.77062996  0.40831616]
 [-0.40558996  0.40831616  1.63436941]]


In [8]:
arr = np.arange(16).reshape((2,2,4))