In [1]:
import numpy as np

tempList = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]

In [2]:
print(tempList)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [3]:
arrayList = np.array(tempList)
print(arrayList)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
evenArray = arrayList[(arrayList%2 == 0)]
print(evenArray)

[ 0  2  4  6  8 10]


In [8]:
sum = sum(evenArray)
print(sum)

30
